version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"
    working_directory: ~/arkecosystem/client
    steps:
      - checkout
      - run:
          name: Install prerequisits
          command: |
            brew install carthage || true
            brew outdated carthage || brew upgrade carthage
      - run:
          name: Navigate to correct folder
          command: cd Client && carthage bootstrap --cache-builds
      - run:
          name: Build and run tests
          command: set -o pipefail && xcodebuild clean test -project Client.xcodeproj -scheme ClientTests CODE_SIGNING_REQUIRED=NO
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
