name: Lint

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
    build:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install
              run: brew install swiftlint
            - name: Lint
              run: cd Client && swiftlint lint --reporter junit
